# Site settings
title: PlayCraft AI
email: info@playcraftai.com
description: >
  PlayCraft AI helps mobile game studios increase player retention and lifetime value (LTV)
  using on-device machine learning and micro-models. Fast, private, and resilient personalization.
  tags: [ml, ai, game-development, leadership, learning, high-dimensional]
date: 2025-10-29 08:00 -0700
published: true

url: "https://playcraftai.com"
baseurl: ""

github_username:  russpatterson

# Author info
author: Russ Patterson
avatar: /assets/images/russpatterson.jpg
bio: "Director of Engineering, Playcraft AI. Building intelligent word games and exploring on-device ML for player happiness."

# Build settings
theme: minima
plugins:
  - jekyll-seo-tag

# Social links
social_links:
  github: https://github.com/russpatterson
  linkedin: https://www.linkedin.com/in/russellpatterson/

timezone: America/Los_Angeles


# Defaults for posts and pages
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Russ Patterson
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

# Navigation links (minima theme)
header_pages:
  - index.md
  - about.md
  - blog.md # optional: if you make a blog landing page

# Exclusions
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
